AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  # Globals define las configuraciones que se aplican a todas las funciones por defecto
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Parameters:
  dbUrl:
    Type: String
    Description: "Database connection URL"

  jwtSecret:
    Type: String
    Description: "Secret key for JWT"
  
  jwtExpiresIn:
    Type: String
    Description: "JWT expiration time"


Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  MailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mail/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
      Events:
        SendMail:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /mail/send
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts



  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        Profile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/profile
            Method: get
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: post
        ChangePassword:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/change-password
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts
        
            
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/
            Method: get
        GetById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/{id}
            Method: get
        GetAllTechnicalUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/technical/{userId}
            Method: get
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/save
            Method: post
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/update
            Method: put
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/delete
            Method: put
        ResetPassword:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/reset-password
            Method: put
        AssignTechnical:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/assign-technical
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts



  RoleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: role/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetAllRoles:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/
            Method: get 
        GetRoleById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/{id}
            Method: get
        GetPermissionsByRoleId:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/permissions/{roleId}
            Method: get
        CreateRole:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/save
            Method: post
        UpdateRole:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/update
            Method: put 
        AssignPermissionToRole:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/assign-permission
            Method: post
        DeleteRole:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /role/delete
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts


  ConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: configurations/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetAllConfigs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configuration/
            Method: get
        GetConfigById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configuration/{id}
            Method: get
        UpdateConfig:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configuration/update
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts

  ClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: client/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetAllClients:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/
            Method: get
        GetClientById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/{id}
            Method: get
        CreateClient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/save
            Method: post
        UpdateClient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/update
            Method: put
        DeleteClient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/delete
            Method: put
        GetSitesByClientId:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/sites-by-client/{id}
            Method: get
        GetSiteBySiteId:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/site/{id}
            Method: get
        CreateSite:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/site/save
            Method: post
        UpdateSite:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/site/update
            Method: put
        DeleteSite:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /client/site/delete
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts


  technicalVisitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: technical-visit/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetAllTechnicalVisits:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /technical-visit/
            Method: get
        GetTechnicalVisitById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /technical-visit/{id}
            Method: get
        UpdateStatusInitVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /technical-visit/init
            Method: post
        OperationCheckInVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /technical-visit/check-in
            Method: post
        OperationCheckOutVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /technical-visit/check-out
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts
          
  configVisitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: config-visit/
      Handler: index.handler
      Environment:
        Variables:
          DB_URL: !Ref dbUrl
          JWT_SECRET: !Ref jwtSecret
          JWT_EXPIRES_IN: !Ref jwtExpiresIn
      Events:
        GetVisitById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/visit/{id}
            Method: get
        GetSupervisors:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/supervisors
            Method: get
        GetTechniciansBySupervisor:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/technicians-by-supervisor/{id}
            Method: get
        GetClientsActive:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/clients-active/
            Method: get
        GetActiveLocationsByClient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/active-locations-by-client/{id}
            Method: get
        CreateVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/create-visit
            Method: post
        UpdateVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/update-visit
            Method: put
        CancelVisit:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /config-visit/cancel-visit
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - index.ts



# Outputs define las salidas que se mostrarán al finalizar el despliegue
Outputs:
  ProjectEndpoint:
    Description: "API endpoint URL for dev stage"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

