AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  # Globals define las configuraciones que se aplican a todas las funciones por defecto
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: nodejs22.x
    Architectures:
      - arm64

Parameters:
  dbUrl:
    Type: String
    Description: "Database connection URL"

  jwtSecret:
    Type: String
    Description: "Secret key for JWT"
  
  jwtExpiresIn:
    Type: String
    Description: "JWT expiration time"


Resources:


  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: index.handler
      Events:
        Profile:
          Type: Api
          Properties:
            Path: /auth/profile
            Method: get
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
        ChangePassword:
          Type: Api
          Properties:
            Path: /auth/change-password
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true             
        Target: "es2022"        
        Sourcemap: false        
        EntryPoints:
          - index.ts 


# Outputs define las salidas que se mostrarán al finalizar el despliegue
Outputs:
  ProjectEndpoint:
    Description: "API endpoint URL for dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
